pipeline {
  agent any
  libraries {
    lib('fxtest@1.10')
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 5, unit: 'MINUTES')
  }
  stages {
    stage('Lint') {
      agent {
        dockerfile {
          dir 'tests'
        }
      }
      steps {
        sh "flake8 tests/"
      }
    }
    stage('Test') {
      agent {
        dockerfile {
          dir 'tests'
        }
      }
      environment {
        PYTEST_PROCESSES = "${PYTEST_PROCESSES ?: "auto"}"
        PULSE = credentials('PULSE')
      }
      steps {
        sh "pytest " +
          "-n=${PYTEST_PROCESSES} " +
          "--color=yes " + 
          "--junit-xml=tests/results/junit.xml --html=tests/results/index.html --self-contained-html " +
          "--log-raw=tests/results/raw.txt " +
          "--log-tbpl=tests/results/tbpl.txt " +
          "tests"
      }
      post {
        always {
          stash includes: 'tests/results/*', name: 'results'
          archiveArtifacts 'tests/results/*'
          junit 'tests/results/*.xml'
          submitToActiveData('tests/results/raw.txt')
          submitToTreeherder('snippets-service', 'e2e', 'End-to-end integration tests', 'tests/results/*', 'tests/results/tbpl.txt')
        }
      }
    }
  }
  post {
    always {
      unstash 'results'
    }
    changed {
      ircNotification('#snippets')
      ircNotification('#fx-test-alerts')
    }
    failure {
      emailext(
        attachLog: true,
        attachmentsPattern: 'tests/results/index.html',
        body: '$BUILD_URL\n\n$FAILED_TESTS',
        replyTo: '$DEFAULT_REPLYTO',
        subject: '$DEFAULT_SUBJECT',
        to: '$DEFAULT_RECIPIENTS')
    }
  }
}
