pipeline {
  agent any
  libraries {
    lib('fxtest@1.9')
  }
  options {
    ansiColor('xterm')
    timestamps()
    timeout(time: 5, unit: 'MINUTES')
  }
  environment {
    PYTEST_ADDOPTS = "-n=10 --color=yes"
    PULSE = credentials('PULSE')
  }
  stages {
    stage('Lint') {
      steps {
        sh "tox -c tests/tox.ini -e flake8"
      }
    }
    stage('Test') {
      steps {
        sh "tox -c tests/tox.ini -e py27"
      }
      post {
        always {
          archiveArtifacts 'tests/results/*'
          junit 'tests/results/*.xml'
          submitToActiveData('tests/results/py27_raw.txt')
          submitToTreeherder('snippets-service', 'e2e', 'End-to-end integration tests', 'tests/results/*', 'tests/results/py27_tbpl.txt')
        }
      }
    }
  }
  post {
    failure {
      mail(
        body: "${BUILD_URL}",
        from: "firefox-test-engineering@mozilla.com",
        replyTo: "firefox-test-engineering@mozilla.com",
        subject: "Build failed in Jenkins: ${JOB_NAME} #${BUILD_NUMBER}",
        to: "fte-ci@mozilla.com")
    }
    changed {
      ircNotification('#snippets')
      ircNotification('#fx-test-alerts')
    }
  }
}
