# Generated by Django 2.2.3 on 2019-07-25 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20190718_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asrsnippet',
            name='for_qa',
        ),
    ]
