# Generated by Django 2.2.3 on 2019-07-31 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_asrsnippet_for_qa'),
    ]

    operations = [
        migrations.AddField(
            model_name='simplebelowsearchtemplate',
            name='button_background_color',
            field=models.CharField(blank=True, help_text='The text color of the button. Valid CSS color.', max_length=20),
        ),
        migrations.AddField(
            model_name='simplebelowsearchtemplate',
            name='button_color',
            field=models.CharField(blank=True, help_text='The text color of the button. Valid CSS color.', max_length=20),
        ),
        migrations.AddField(
            model_name='simplebelowsearchtemplate',
            name='button_label',
            field=models.CharField(blank=True, help_text='Text for a button next to main snippet text that links to button_url. Requires button_url.', max_length=50),
        ),
        migrations.AddField(
            model_name='simplebelowsearchtemplate',
            name='button_url',
            field=models.URLField(blank=True, help_text='A url, button_label links to this', max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AddField(
            model_name='simplebelowsearchtemplate',
            name='title',
            field=models.CharField(blank=True, help_text='Snippet title displayed before snippet text.', max_length=255),
        ),
    ]
