# Generated by Django 2.2.3 on 2019-08-01 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0005_auto_20190731_1023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='asrsnippet',
            name='status',
            field=models.IntegerField(choices=[(100, 'Draft'), (200, 'Ready for review'), (300, 'Approved')], db_index=True, default=100, verbose_name='Content Status'),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (100, 'Scheduled'), (200, 'Published'), (300, 'Canceled'), (400, 'Completed')], db_index=True, default=0, editable=False)),
                ('weight', models.IntegerField(choices=[(2, 'Appear 1/50th as often as an average snippet'), (5, 'Appear 1/20th as often as an average snippet'), (10, 'Appear 1/10th as often as an average snippet'), (33, 'Appear 1/3rd as often as an average snippet'), (50, 'Appear half as often as an average snippet'), (66, 'Appear 2/3rds as often as an average snippet'), (100, 'Appear as often as an average snippet'), (150, 'Appear 1.5 times as often as an average snippet'), (200, 'Appear twice as often as an average snippet'), (300, 'Appear three times as often as an average snippet')], default=100, help_text='How often should this snippet be shown to users?')),
                ('publish_start', models.DateTimeField(blank=True, help_text='See the current time in <a target="_blank" href="https://time.is/UTC">UTC</a>', null=True, verbose_name='Publish Starts')),
                ('publish_end', models.DateTimeField(blank=True, help_text='See the current time in <a target="_blank" href="https://time.is/UTC">UTC</a>', null=True, verbose_name='Publish Ends')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='base.Campaign')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='base.ASRSnippet')),
                ('targets', models.ManyToManyField(default=None, related_name='jobs', to='base.Target')),
            ],
            options={
                'ordering': ('-publish_start', '-publish_end'),
            },
        ),
    ]
