# Generated by Django 2.2.3 on 2019-08-30 10:18

from django.db import migrations
import snippets.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20190801_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='donation_form_url',
            field=snippets.base.fields.URLField(default='https://donate.mozilla.org/?utm_source=desktop-snippet&utm_medium=snippet', max_length=500, verbose_name='Donation Form URL'),
        ),
        migrations.AlterField(
            model_name='simplebelowsearchtemplate',
            name='button_url',
            field=snippets.base.fields.URLField(blank=True, help_text='A url, button_label links to this', max_length=500, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='button_url',
            field=snippets.base.fields.URLField(blank=True, help_text='A url, button_label links to this', max_length=500, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='section_title_url',
            field=snippets.base.fields.URLField(blank=True, help_text='A url, section_title_text links to this', max_length=500, verbose_name='Section Title URL'),
        ),
    ]
