# Generated by Django 2.2.3 on 2019-08-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20190830_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='distributions',
            field=models.CharField(default=',default,', help_text='Comma separated list of distributions. Defaults to `default`', max_length=500),
        ),
    ]
