# Generated by Django 2.2.3 on 2019-09-05 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_job_distributions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asrsnippet',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='asrsnippet',
            name='publish_end',
        ),
        migrations.RemoveField(
            model_name='asrsnippet',
            name='publish_start',
        ),
        migrations.RemoveField(
            model_name='asrsnippet',
            name='targets',
        ),
        migrations.RemoveField(
            model_name='asrsnippet',
            name='weight',
        ),
    ]
