# Generated by Django 2.2.4 on 2019-09-04 15:19

from django.db import migrations, models
import django.db.models.deletion
import snippets.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_job_distributions'),
    ]

    operations = [
        migrations.AddField(
            model_name='fxasignuptemplate',
            name='scene1_section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 16x16px. PNG. scene1_section_title_text must also be specified to display.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fxa_scene1_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AddField(
            model_name='fxasignuptemplate',
            name='scene1_section_title_text',
            field=models.CharField(blank=True, help_text='Section title text. scene1_section_title_icon must also be specified to display.', max_length=255, verbose_name='Section Title Text'),
        ),
        migrations.AddField(
            model_name='fxasignuptemplate',
            name='scene1_section_title_url',
            field=snippets.base.fields.URLField(blank=True, help_text='A url, scene1_section_title_text links to this', max_length=500, verbose_name='Section Title URL'),
        ),
        migrations.AddField(
            model_name='newslettertemplate',
            name='scene1_section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 16x16px. PNG. scene1_section_title_text must also be specified to display.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newsletter_scene1_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AddField(
            model_name='newslettertemplate',
            name='scene1_section_title_text',
            field=models.CharField(blank=True, help_text='Section title text. scene1_section_title_icon must also be specified to display.', max_length=255, verbose_name='Section Title Text'),
        ),
        migrations.AddField(
            model_name='newslettertemplate',
            name='scene1_section_title_url',
            field=snippets.base.fields.URLField(blank=True, help_text='A url, scene1_section_title_text links to this', max_length=500, verbose_name='Section Title URL'),
        ),
        migrations.AddField(
            model_name='sendtodevicetemplate',
            name='scene1_section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 16x16px. PNG. scene1_section_title_text must also be specified to display.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sendtodevice_scene1_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AddField(
            model_name='sendtodevicetemplate',
            name='scene1_section_title_text',
            field=models.CharField(blank=True, help_text='Section title text. scene1_section_title_icon must also be specified to display.', max_length=255, verbose_name='Section Title Text'),
        ),
        migrations.AddField(
            model_name='sendtodevicetemplate',
            name='scene1_section_title_url',
            field=snippets.base.fields.URLField(blank=True, help_text='A url, scene1_section_title_text links to this', max_length=500, verbose_name='Section Title URL'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 16x16px. PNG. section_title_text must also be specified to display.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='simple_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
    ]
