# Generated by Django 2.2.4 on 2019-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20190916_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettertemplate',
            name='retry_button_label',
            field=models.CharField(default='Try again', help_text='Button label after a failed form submission', max_length=50, verbose_name='Retry Button Label'),
        ),
        migrations.AddField(
            model_name='sendtodevicetemplate',
            name='retry_button_label',
            field=models.CharField(default='Try again', help_text='Button label after a failed form submission', max_length=50, verbose_name='Retry Button Label'),
        ),
    ]
