# Generated by Django 2.2.4 on 2019-10-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190916_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='filtr_total_addons',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
