# Generated by Django 2.2.4 on 2019-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20190916_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='on_linux',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Linux'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='on_macos',
            field=models.BooleanField(db_index=True, default=True, verbose_name='macOS'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='on_windows',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Windows'),
        ),
        migrations.AddField(
            model_name='target',
            name='on_linux',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Linux'),
        ),
        migrations.AddField(
            model_name='target',
            name='on_macos',
            field=models.BooleanField(db_index=True, default=True, verbose_name='macOS'),
        ),
        migrations.AddField(
            model_name='target',
            name='on_windows',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Windows'),
        ),
    ]
