# Generated by Django 2.2.4 on 2019-10-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_target_filtr_total_addons'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='filtr_can_install_addons',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
