# Generated by Django 2.2.4 on 2019-10-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20191008_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='filtr_firefox_service',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
