# Generated by Django 2.2.6 on 2019-10-11 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_target_filtr_firefox_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='filtr_operating_system',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
