# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_snippet_on_startpage_5'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonsnippet',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='priority',
        ),
    ]
