# Generated by Django 2.2.6 on 2019-10-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20191021_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='completed_on',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
