# Generated by Django 2.2.6 on 2019-10-30 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_job_completed_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyJobMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fetched_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(editable=False)),
                ('impressions', models.PositiveIntegerField(default=0, editable=False)),
                ('clicks', models.PositiveIntegerField(default=0, editable=False)),
                ('blocks', models.PositiveIntegerField(default=0, editable=False)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Job')),
            ],
            options={
                'verbose_name_plural': 'Daily Job Metrics',
                'unique_together': {('job', 'date')},
            },
        ),
    ]
