# Generated by Django 2.2.6 on 2019-11-19 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_dailyjobmetrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrsnippet',
            options={'ordering': ['-modified'], 'verbose_name': 'ASR Snippet', 'verbose_name_plural': 'ASR Snippets'},
        ),
    ]
