# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20171024_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippettemplatevariable',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
