# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_snippettemplatevariable_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippettemplatevariable',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='jsonsnippet',
            name='on_esr',
            field=models.BooleanField(default=False, verbose_name=b'Enterprise'),
        ),
        migrations.AddField(
            model_name='snippet',
            name='on_esr',
            field=models.BooleanField(default=False, verbose_name=b'Enterprise'),
        ),
    ]
