# Generated by Django 2.2.6 on 2019-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20191211_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailychannelmetrics',
            name='channel',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailychannelmetrics',
            name='date',
            field=models.DateField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='dailycountrymetrics',
            name='country',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dailycountrymetrics',
            name='date',
            field=models.DateField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='dailyjobmetrics',
            name='date',
            field=models.DateField(db_index=True, editable=False),
        ),
        migrations.AlterField(
            model_name='dailysnippetmetrics',
            name='date',
            field=models.DateField(db_index=True, editable=False),
        ),
    ]
