# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-25 10:41
from __future__ import unicode_literals

from django.db import migrations


def set_is_developer(apps, schema_editor):
    # Part the Dynamic Column Removal Effort (Issue #940)
    pass


def noop(apps, schema_editor):
    # nothing needed to go back in time.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_snippettemplatevariable_order'),
    ]

    operations = [
        migrations.RunPython(set_is_developer, noop),
    ]
