# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_auto_20180426_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_2',
            field=models.BooleanField(default=False, verbose_name=b'Version 2'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_3',
            field=models.BooleanField(default=False, verbose_name=b'Version 3'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_4',
            field=models.BooleanField(default=False, verbose_name=b'Version 4'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_5',
            field=models.BooleanField(default=True, verbose_name=b'Activity Stream'),
        ),
    ]
