# Generated by Django 2.2.6 on 2020-02-19 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_locale_rtl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrsnippet',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snippets', to='base.Category'),
        ),
    ]
