# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-15 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20180426_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsonsnippet',
            name='on_esr',
            field=models.BooleanField(default=False, verbose_name=b'ESR'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_esr',
            field=models.BooleanField(default=False, verbose_name=b'ESR'),
        ),
    ]
