# Generated by Django 2.2.6 on 2020-02-21 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20200219_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrsnippet',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snippets', to='base.Product'),
        ),
    ]
