# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 13:32
from __future__ import unicode_literals

from django.db import migrations


def migrate_has_testpilot(apps, schema_editor):
    # Part the Dynamic Column Removal Effort (Issue #940)
    pass


def noop(apps, schema_editor):
    # nothing needed to go back in time.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20180515_0733'),
    ]

    operations = [
        migrations.RunPython(migrate_has_testpilot, noop),
    ]
