# Generated by Django 2.2.10 on 2020-03-03 13:28

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20200221_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyImpressions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fetched_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True, editable=False, unique=True)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default=dict, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='JobDailyPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fetched_on', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(db_index=True, editable=False)),
                ('impression', models.PositiveIntegerField(default=0, editable=False)),
                ('adj_impression', models.PositiveIntegerField(default=0, editable=False)),
                ('click', models.PositiveIntegerField(default=0, editable=False)),
                ('block', models.PositiveIntegerField(default=0, editable=False)),
                ('dismiss', models.PositiveIntegerField(default=0, editable=False)),
                ('go_to_scene2', models.PositiveIntegerField(default=0, editable=False)),
                ('subscribe_success', models.PositiveIntegerField(default=0, editable=False)),
                ('subscribe_error', models.PositiveIntegerField(default=0, editable=False)),
                ('other_click', models.PositiveIntegerField(default=0, editable=False)),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='base.Job')),
            ],
            options={
                'unique_together': {('job', 'date')},
            },
        ),
        migrations.DeleteModel(
            name='DailySnippetMetrics',
        ),
    ]
