# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_auto_20180508_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsonsnippet',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='snippet',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
