# Generated by Django 2.2.10 on 2020-03-23 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20200303_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DailyChannelMetrics',
        ),
        migrations.DeleteModel(
            name='DailyCountryMetrics',
        ),
        migrations.DeleteModel(
            name='DailyJobMetrics',
        ),
    ]
