# Generated by Django 2.2.10 on 2020-05-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20200323_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='client_match_rules',
        ),
    ]
