# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-21 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20180521_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonsnippet',
            name='disabled',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='disabled',
        ),
    ]
