# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_auto_20180718_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='on_startpage_6',
            field=models.BooleanField(default=False, verbose_name=b'Activity Stream NG'),
        ),
    ]
