# Generated by Django 2.2.10 on 2020-06-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20200513_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='distributionbundle',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='distribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='base.Distribution'),
        ),
    ]
