# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_snippet_on_startpage_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippettemplate',
            name='code_name',
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
