# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 17:41
from __future__ import unicode_literals

from django.db import migrations


def set_default_template_code_names(apps, schema_editor):
    SnippetTemplate = apps.get_model('base', 'SnippetTemplate')
    for template in SnippetTemplate.objects.all():
        template.code_name = '{}'.format(template.id)
        template.save()


def noop(apps, schema_editor):
    # nothing needed to go back in time.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_snippettemplate_code_name'),
    ]

    operations = [
        migrations.RunPython(set_default_template_code_names, noop)
    ]
