# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-07 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_snippettemplate_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnippetNG',
            fields=[
            ],
            options={
                'verbose_name': 'Snippet NG',
                'proxy': True,
                'verbose_name_plural': 'Snippets NG',
                'indexes': [],
            },
            bases=('base.snippet',),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_5',
            field=models.BooleanField(default=False, verbose_name=b'Activity Stream'),
        ),
        migrations.AlterField(
            model_name='snippettemplate',
            name='code_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
