# Generated by Django 2.2.13 on 2020-10-14 04:05

from django.db import migrations, models
import snippets.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_sendtodevicesinglescenetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='fundraising_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='fundraising_title_icons', to='base.Icon', verbose_name='Title Icon'),
        ),
        migrations.AlterField(
            model_name='fxasignuptemplate',
            name='scene1_icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='fxasignup_scene1_icons', to='base.Icon', verbose_name='Scene 1 Icon'),
        ),
        migrations.AlterField(
            model_name='fxasignuptemplate',
            name='scene1_section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 64x64px. PNG. scene1_section_title_text must also be specified to display.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='fxa_scene1_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AlterField(
            model_name='fxasignuptemplate',
            name='scene1_title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='fxasignup_scene1_title_icons', to='base.Icon', verbose_name='Scene 1 Title Icon'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='scene1_icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='newsletter_scene1_icons', to='base.Icon', verbose_name='Scene 1 Icon'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='scene1_section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 64x64px. PNG. scene1_section_title_text must also be specified to display.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='newsletter_scene1_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='scene1_title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='newsletter_scene1_title_icons', to='base.Icon', verbose_name='Scene 1 Title Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicesinglescenetemplate',
            name='icon',
            field=models.ForeignKey(help_text='Image to display above the form. 192x192px PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='sendtodevicesinglescene_icons', to='base.Icon', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicesinglescenetemplate',
            name='section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 64x64px. PNG. section_title_text must also be specified to display.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='sendtodevicesinglescene_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='scene1_icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192 PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='sendtodevice_scene1_icons', to='base.Icon', verbose_name='Scene 1 Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='scene1_section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 64x64px. PNG. scene1_section_title_text must also be specified to display.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='sendtodevice_scene1_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='scene1_title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='sendtodevice_scene1_title_icons', to='base.Icon', verbose_name='Scene 1 Title Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='scene2_icon',
            field=models.ForeignKey(help_text='Image to display above the form. 192x192px PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='sendtodevice_scene2_icons', to='base.Icon', verbose_name='Scene 2 Icon'),
        ),
        migrations.AlterField(
            model_name='simplebelowsearchtemplate',
            name='icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='simple_below_search_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='simple_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 64x64px. PNG. section_title_text must also be specified to display.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='simple_section_icons', to='base.Icon', verbose_name='Section Title Icon'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=snippets.base.models.Icon.check_if_icon_can_be_deleted, related_name='simple_title_icons', to='base.Icon', verbose_name='Title Icon'),
        ),
    ]
