# Generated by Django 2.2.13 on 2020-10-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20201014_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdailyperformance',
            name='adj_client_percentage',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='jobdailyperformance',
            name='adj_impression_percentage',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
