# Generated by Django 2.2.13 on 2020-10-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20201012_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='adj_impression_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='adj_impression_no_clients_total',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='block_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='block_no_clients_total',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='click_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='click_no_clients_total',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='dismiss_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='dismiss_no_clients_total',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='go_to_scene2_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='go_to_scene2_no_clients_total',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='impression_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='other_click_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='other_click_no_clients_total',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='subscribe_error_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='subscribe_error_no_clients_total',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='subscribe_success_no_clients',
        ),
        migrations.RemoveField(
            model_name='jobdailyperformance',
            name='subscribe_success_no_clients_total',
        ),
    ]
