# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 10:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_snippettemplate_startpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('-modified',), 'permissions': (('can_publish_on_release', 'Can publish snippets on Release'), ('can_publish_on_beta', 'Can publish snippets on Beta'), ('can_publish_on_aurora', 'Can publish snippets on Aurora'), ('can_publish_on_nightly', 'Can publish snippets on nightly'), ('can_publish_on_esr', 'Can publish snippets on ESR'))},
        ),
    ]
