# Generated by Django 2.2.13 on 2020-11-04 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20201014_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='client_match_rules',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='exclude_from_search_providers',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='locales',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='template',
        ),
        migrations.RemoveField(
            model_name='snippettemplatevariable',
            name='template',
        ),
        migrations.DeleteModel(
            name='ClientMatchRule',
        ),
        migrations.DeleteModel(
            name='SearchProvider',
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.DeleteModel(
            name='SnippetTemplate',
        ),
        migrations.DeleteModel(
            name='SnippetTemplateVariable',
        ),
        migrations.DeleteModel(
            name='TargetedLocale',
        ),
    ]
