# Generated by Django 2.1 on 2018-08-20 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20180604_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ('-modified',), 'permissions': (('can_publish_on_release', 'Can publish snippets on Release'), ('can_publish_on_beta', 'Can publish snippets on Beta'), ('can_publish_on_aurora', 'Can publish snippets on Aurora'), ('can_publish_on_nightly', 'Can publish snippets on Nightly'), ('can_publish_on_esr', 'Can publish snippets on ESR'))},
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='client_match_rules',
            field=models.ManyToManyField(blank=True, to='base.ClientMatchRule', verbose_name='Client Match Rules'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='countries',
            field=models.ManyToManyField(blank=True, to='base.TargetedCountry', verbose_name='Targeted Countries'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='icon',
            field=models.TextField(help_text='Icon should be a 96x96px PNG.'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='locales',
            field=models.ManyToManyField(blank=True, to='base.TargetedLocale', verbose_name='Targeted Locales'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='on_aurora',
            field=models.BooleanField(default=False, verbose_name='Aurora'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='on_beta',
            field=models.BooleanField(default=False, verbose_name='Beta'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='on_esr',
            field=models.BooleanField(default=False, verbose_name='ESR'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='on_nightly',
            field=models.BooleanField(default=False, verbose_name='Nightly'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='on_release',
            field=models.BooleanField(default=True, verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='on_startpage_1',
            field=models.BooleanField(default=True, verbose_name='Version 1'),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='text',
            field=models.CharField(help_text='Maximum length 140 characters.', max_length=140),
        ),
        migrations.AlterField(
            model_name='jsonsnippet',
            name='weight',
            field=models.IntegerField(choices=[(33, 'Appear 1/3rd as often as an average snippet'), (50, 'Appear half as often as an average snippet'), (66, 'Appear 2/3rds as often as an average snippet'), (100, 'Appear as often as an average snippet'), (150, 'Appear 1.5 times as often as an average snippet'), (200, 'Appear twice as often as an average snippet'), (300, 'Appear three times as often as an average snippet')], default=100, help_text='How often should this snippet be shown to users?', verbose_name='Prevalence'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='campaign',
            field=models.CharField(blank=True, default='', help_text='Optional campaign name. Will be added in the stats ping. Will be used for snippet blocking if set.', max_length=255),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='client_match_rules',
            field=models.ManyToManyField(blank=True, to='base.ClientMatchRule', verbose_name='Client Match Rules'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='countries',
            field=models.ManyToManyField(blank=True, to='base.TargetedCountry', verbose_name='Targeted Countries'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='data',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='exclude_from_search_providers',
            field=models.ManyToManyField(blank=True, to='base.SearchProvider', verbose_name='Excluded Search Providers'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='locales',
            field=models.ManyToManyField(blank=True, to='base.TargetedLocale', verbose_name='Targeted Locales'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_aurora',
            field=models.BooleanField(default=False, verbose_name='Aurora'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_beta',
            field=models.BooleanField(default=False, verbose_name='Beta'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_esr',
            field=models.BooleanField(default=False, verbose_name='ESR'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_nightly',
            field=models.BooleanField(default=False, verbose_name='Nightly'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_release',
            field=models.BooleanField(default=False, verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_1',
            field=models.BooleanField(default=False, verbose_name='Version 1'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_2',
            field=models.BooleanField(default=False, verbose_name='Version 2'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_3',
            field=models.BooleanField(default=False, verbose_name='Version 3'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_4',
            field=models.BooleanField(default=False, verbose_name='Version 4'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_5',
            field=models.BooleanField(default=False, verbose_name='Activity Stream'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_6',
            field=models.BooleanField(default=False, verbose_name='Activity Stream NG'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.SnippetTemplate'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='weight',
            field=models.IntegerField(choices=[(33, 'Appear 1/3rd as often as an average snippet'), (50, 'Appear half as often as an average snippet'), (66, 'Appear 2/3rds as often as an average snippet'), (100, 'Appear as often as an average snippet'), (150, 'Appear 1.5 times as often as an average snippet'), (200, 'Appear twice as often as an average snippet'), (300, 'Appear three times as often as an average snippet')], default=100, help_text='How often should this snippet be shown to users?', verbose_name='Prevalence'),
        ),
        migrations.AlterField(
            model_name='snippettemplate',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hide from template selection dropdown'),
        ),
        migrations.AlterField(
            model_name='snippettemplate',
            name='priority',
            field=models.BooleanField(default=False, help_text='Set to true to display first in dropdowns for faster selections', verbose_name='Priority template'),
        ),
        migrations.AlterField(
            model_name='snippettemplatevariable',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='snippettemplatevariable',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_set', to='base.SnippetTemplate'),
        ),
        migrations.AlterField(
            model_name='snippettemplatevariable',
            name='type',
            field=models.IntegerField(choices=[(4, 'Main Text'), (0, 'Text'), (2, 'Small Text'), (1, 'Image'), (3, 'Checkbox')], default=0),
        ),
        migrations.AlterField(
            model_name='targetedcountry',
            name='code',
            field=models.CharField(max_length=16, unique=True, verbose_name='Geolocation Country'),
        ),
    ]
