# Generated by Django 2.2.13 on 2020-10-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20201104_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='filtr_channels',
            field=models.CharField(default='release;', max_length=255),
        ),
    ]
