# Generated by Django 2.2.13 on 2020-10-26 12:55

from django.db import migrations
from django.db.models import Q

def forwards(apps, schema_editor):
    Target = apps.get_model('base', 'Target')
    from snippets.base.forms import TargetAdminForm
    for target in Target.objects.filter(
            Q(on_release=True) | \
            Q(on_esr=True) | \
            Q(on_beta=True) | \
            Q(on_aurora=True) | \
            Q(on_nightly=True)):

        value = ''
        for key in ['release', 'esr', 'beta', 'aurora', 'nightly']:
            if getattr(target, f'on_{key}', False):
                value += f'{key};'
        value = value.strip(';')

        target.filtr_channels = value
        f = TargetAdminForm(instance=target)
        target.jexl_expr = f.generate_jexl_expr(f.initial)
        target.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_target_filtr_channel'),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
