# Generated by Django 2.1 on 2018-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20180820_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='on_aurora',
            field=models.BooleanField(default=False, verbose_name='Dev Edition (old Aurora)'),
        ),
    ]
