# Generated by Django 2.1 on 2018-09-17 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0045_auto_20180822_0859'),
    ]

    operations = [
        migrations.CreateModel(
            name='ASRSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('data', models.TextField(default='{}')),
                ('status', models.IntegerField(choices=[(100, 'Draft'), (200, 'Ready for review'), (300, 'Disabled'), (400, 'Enabled')], db_index=True, default=100)),
            ],
            options={
                'verbose_name': 'ASR Snippet',
                'verbose_name_plural': 'ASR Snippets',
                'ordering': ['-modified'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, default='', help_text='Optional campaign slug. Will be added in the stats ping. Will be used for snippet blocking if set.', max_length=255, unique=True)),
                ('publish_start', models.DateTimeField(blank=True, help_text='See the current time in <a href="http://time.is/UTC">UTC</a>', null=True, verbose_name='Publish Starts')),
                ('publish_end', models.DateTimeField(blank=True, help_text='See the current time in <a href="http://time.is/UTC">UTC</a>', null=True, verbose_name='Publish Ends')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('on_release', models.BooleanField(db_index=True, default=False, verbose_name='Release')),
                ('on_beta', models.BooleanField(db_index=True, default=False, verbose_name='Beta')),
                ('on_aurora', models.BooleanField(db_index=True, default=False, verbose_name='Dev Edition (old Aurora)')),
                ('on_nightly', models.BooleanField(db_index=True, default=False, verbose_name='Nightly')),
                ('on_esr', models.BooleanField(db_index=True, default=False, verbose_name='ESR')),
                ('on_startpage_6', models.BooleanField(db_index=True, default=True, verbose_name='Activity Stream Router')),
                ('jexl', django_mysql.models.DynamicField(default={})),
                ('jexl_expr', models.TextField(blank=True, default='')),
                ('client_match_rules', models.ManyToManyField(blank=True, to='base.ClientMatchRule', verbose_name='Client Match Rules')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Target'),
        ),
        migrations.AddField(
            model_name='asrsnippet',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Campaign'),
        ),
        migrations.AddField(
            model_name='asrsnippet',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asrsnippet',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.SnippetTemplate'),
        ),
    ]
