# Generated by Django 2.2.13 on 2020-10-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20201026_1255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='on_aurora',
        ),
        migrations.RemoveField(
            model_name='target',
            name='on_beta',
        ),
        migrations.RemoveField(
            model_name='target',
            name='on_esr',
        ),
        migrations.RemoveField(
            model_name='target',
            name='on_nightly',
        ),
        migrations.RemoveField(
            model_name='target',
            name='on_release',
        ),
        migrations.AlterField(
            model_name='target',
            name='filtr_channels',
            field=models.CharField(default='', max_length=255),
        ),
    ]
