# Generated by Django 2.1.1 on 2018-09-24 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20180919_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippettemplatevariable',
            name='type',
            field=models.IntegerField(choices=[(4, 'Main Text'), (5, 'Rich Text'), (0, 'Text'), (2, 'Small Text'), (1, 'Image'), (3, 'Checkbox')], default=0),
        ),
    ]
