# Generated by Django 2.1.1 on 2018-10-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_snippet_ready_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrsnippet',
            name='locales',
            field=models.ManyToManyField(blank=True, to='base.TargetedLocale', verbose_name='Targeted Locales'),
        ),
    ]
