# Generated by Django 2.1.2 on 2018-10-09 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0054_asrsnippet_locales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SnippetNG',
        ),
        migrations.RemoveField(
            model_name='snippet',
            name='on_startpage_6',
        ),
    ]
