# Generated by Django 2.1.1 on 2018-10-01 09:37

from django.db import migrations


def migrate_country_code_to_uppercase(apps, schema_editor):
    TargetedCountry = apps.get_model('base', 'TargetedCountry')

    for country in TargetedCountry.objects.all():
        country.code = country.code.upper()
        country.save()


def migrate_country_code_to_lowercase(apps, schema_editor):
    TargetedCountry = apps.get_model('base', 'TargetedCountry')

    for country in TargetedCountry.objects.all():
        country.code = country.code.lower()
        country.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20181009_1234'),
    ]

    operations = [
        migrations.RunPython(migrate_country_code_to_uppercase,
                             migrate_country_code_to_lowercase)
    ]
