# Generated by Django 2.1.2 on 2018-10-18 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20181001_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='on_aurora',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Dev Edition (old Aurora)'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_beta',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Beta'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_esr',
            field=models.BooleanField(db_index=True, default=False, verbose_name='ESR'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_nightly',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Nightly'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_release',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Release'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_4',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Version 4'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='on_startpage_5',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Activity Stream'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='published',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
