# Generated by Django 2.1.3 on 2018-11-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_snippet_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrsnippet',
            name='for_qa',
            field=models.BooleanField(blank=True, default=False, help_text='Snippet used in QA Testing. Do not remove or unpublish.', verbose_name='For QA'),
        ),
    ]
