# Generated by Django 2.1.3 on 2018-11-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_auto_20181119_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrsnippet',
            name='publish_end',
            field=models.DateTimeField(blank=True, help_text='See the current time in <a target="_blank" href="http://time.is/UTC">UTC</a>', null=True, verbose_name='Publish Ends'),
        ),
        migrations.AlterField(
            model_name='asrsnippet',
            name='publish_start',
            field=models.DateTimeField(blank=True, help_text='See the current time in <a target="_blank" href="http://time.is/UTC">UTC</a>', null=True, verbose_name='Publish Starts'),
        ),
    ]
