# Generated by Django 2.1.3 on 2018-11-16 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0061_auto_20181116_0810'),
    ]

    operations = [
        migrations.RunSQL(['ALTER TABLE base_asrsnippet AUTO_INCREMENT=10500;'], [''])
    ]
