# Generated by Django 2.1.3 on 2018-12-08 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0062_set_asrsnippet_id_autoincrement_starting_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='asrsnippet',
            name='targets',
            field=models.ManyToManyField(blank=True, default=None, to='base.Target'),
        ),
        migrations.AlterField(
            model_name='asrsnippet',
            name='target',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trgt', to='base.Target'),
        ),
    ]
