# Generated by Django 2.1.3 on 2018-12-08 20:14

from django.db import migrations


def migrate_target_to_targets(apps, schema_editor):
    ASRSnippet = apps.get_model('base', 'ASRSnippet')

    for snippet in ASRSnippet.objects.exclude(target=None):
        snippet.targets.add(snippet.target)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20181208_2012'),
    ]

    operations = [
        migrations.RunPython(migrate_target_to_targets, noop)
    ]
