# Generated by Django 2.1.3 on 2018-12-08 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0064_auto_20181208_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asrsnippet',
            name='target',
        ),
    ]
