# Generated by Django 2.1.3 on 2018-12-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_remove_asrsnippet_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asrsnippet',
            options={'ordering': ['-modified'], 'permissions': (('publish_on_release', 'Publish snippets on Release'), ('publish_on_beta', 'Publish snippets on Beta'), ('publish_on_aurora', 'Publish snippets on Aurora'), ('publish_on_nightly', 'Publish snippets on Nightly'), ('publish_on_esr', 'Publish snippets on ESR')), 'verbose_name': 'ASR Snippet', 'verbose_name_plural': 'ASR Snippets'},
        ),
    ]
