# Generated by Django 2.1.3 on 2019-01-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_auto_20190114_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='migrated_to',
        ),
    ]
