# Generated by Django 2.1.4 on 2019-01-17 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_remove_snippet_migrated_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrsnippet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asrsnippets', to='base.Category'),
        ),
    ]
