# Generated by Django 2.1.5 on 2019-02-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20190117_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(help_text='Optional campaign slug. Will be added in the stats ping. Will be used for snippet blocking if set.', max_length=255, unique=True),
        ),
    ]
