# Generated by Django 2.1.5 on 2019-03-06 10:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import functools
import snippets.base.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0070_auto_20190211_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('height', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(height_field='height', upload_to=functools.partial(snippets.base.models._generate_filename, *(), **{'root': 'icons/'}), width_field='width')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleTemplate',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Template')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField(help_text='Main body text of snippet. HTML subset allowed: i, b, u, strong, em, br')),
                ('button_label', models.CharField(blank=True, max_length=50)),
                ('button_color', models.CharField(blank=True, max_length=20)),
                ('button_url', models.URLField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('section_title_text', models.CharField(blank=True, max_length=255)),
                ('section_title_url', models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['https'])])),
                ('tall', models.BooleanField(blank=True, default=False)),
                ('block_button_text', models.CharField(default='Remove this', max_length=50)),
                ('do_not_autoblock', models.BooleanField(blank=True, default=False)),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icons', to='base.Icon')),
                ('section_title_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_icons', to='base.Icon')),
                ('title_icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='title_icons', to='base.Icon')),
            ],
            bases=('base.template',),
        ),
        migrations.AddField(
            model_name='template',
            name='snippet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_ng', to='base.ASRSnippet'),
        ),
    ]
