# Generated by Django 2.1.5 on 2019-03-12 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20190312_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterTemplate',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Template')),
                ('scene1_title', models.CharField(blank=True, help_text='Snippet title displayed before snippet text.', max_length=255)),
                ('scene1_text', models.TextField(help_text='Main body text of snippet. HTML subset allowed: i, b, u, strong, em, br.')),
                ('scene1_button_label', models.CharField(help_text='Label for the button on Scene 1 that leads to Scene 2.', max_length=50)),
                ('scene1_button_color', models.CharField(blank=True, help_text='The text color of the button. Valid CSS color. Defaults to Firefox Theme Color.', max_length=20)),
                ('scene1_button_background_color', models.CharField(blank=True, help_text='The background color of the button. Valid CSS color. Defaults to Firefox Theme Color.', max_length=20)),
                ('scene2_title', models.CharField(blank=True, help_text='Title displayed before text in scene 2.', max_length=255)),
                ('scene2_text', models.TextField(help_text='Scene 2 main text. HTML subset allowed: i, b, u, strong, em, br.')),
                ('scene2_button_label', models.CharField(default='Sign me up', help_text='Label for form submit button.', max_length=50)),
                ('scene2_email_placeholder_text', models.CharField(default='Your email here', help_text='Value to show while input is empty.', max_length=255)),
                ('scene2_dismiss_button_text', models.CharField(default='Dismiss', help_text='Label for the dismiss button on Scene 2.', max_length=50)),
                ('scene2_newsletter', models.CharField(default='mozilla-foundation', help_text='Newsletter/basket id user is subscribing to. Must be a value from the "Slug" column here: https://basket.mozilla.org/news/.', max_length=50)),
                ('scene2_privacy_html', models.TextField(help_text='Text and link next to the privacy checkbox. Must link to a privacy policy.')),
                ('locale', models.CharField(default='en-US', help_text='String for the newsletter locale code.', max_length=10)),
                ('success_text', models.TextField(help_text='Text of success message after form submission.')),
                ('error_text', models.TextField(help_text='Text of error message if form submission fails.')),
                ('block_button_text', models.CharField(default='Remove this', help_text='Tooltip text used for dismiss button.', max_length=50)),
                ('do_not_autoblock', models.BooleanField(blank=True, default=False, help_text='Used to prevent blocking the snippet after the CTA (link or button) has been clicked.')),
                ('scene1_icon', models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_scene1_icons', to='base.Icon')),
                ('scene1_title_icon', models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='newsletter_scene1_title_icons', to='base.Icon')),
            ],
            bases=('base.template',),
        ),
    ]
