# Generated by Django 2.1.5 on 2019-03-14 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_sendtodevicetemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', on_delete=django.db.models.deletion.PROTECT, related_name='fundraising_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fundraising_title_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='fxasignuptemplate',
            name='scene1_icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', on_delete=django.db.models.deletion.PROTECT, related_name='fxasignup_scene1_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='fxasignuptemplate',
            name='scene1_title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fxasignup_scene1_title_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='scene1_icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', on_delete=django.db.models.deletion.PROTECT, related_name='newsletter_scene1_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='scene1_title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newsletter_scene1_title_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='scene1_icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192 PNG.', on_delete=django.db.models.deletion.PROTECT, related_name='sendtodevice_scene1_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='scene1_title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sendtodevice_scene1_title_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='scene2_icon',
            field=models.ForeignKey(help_text='Image to display above the form. 192x192px PNG.', on_delete=django.db.models.deletion.PROTECT, related_name='sendtodevice_scene2_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='icon',
            field=models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', on_delete=django.db.models.deletion.PROTECT, related_name='simple_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='section_title_icon',
            field=models.ForeignKey(blank=True, help_text='Section title icon. 32x32px. PNG. section_title_text must also be specified to display.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_section_icons', to='base.Icon'),
        ),
        migrations.AlterField(
            model_name='simpletemplate',
            name='title_icon',
            field=models.ForeignKey(blank=True, help_text='Small icon that shows up before the title / text. 64x64px.PNG. Grayscale.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='simple_title_icons', to='base.Icon'),
        ),
    ]
