# Generated by Django 2.1.7 on 2019-03-18 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20190314_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrsnippet',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='base.SnippetTemplate'),
        ),
    ]
