# Generated by Django 2.1.7 on 2019-03-18 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20190318_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='snippet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='template_relation', to='base.ASRSnippet'),
        ),
    ]
