# Generated by Django 2.1.7 on 2019-03-21 13:50

from django.db import migrations, models
import functools
import snippets.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20190318_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='monthly_checkbox_label_text',
            field=models.CharField(default='Make my donation monthly', max_length=255),
        ),
        migrations.AlterField(
            model_name='fxasignuptemplate',
            name='scene1_button_label',
            field=models.CharField(default='Learn more', help_text='Label for the button on Scene 1 that leads to Scene 2.', max_length=50),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(height_field='height', help_text='PNGs only. Note that updating the image will update all snippets using this image.', upload_to=functools.partial(snippets.base.models._generate_filename, *(), **{'root': 'icons/'}), width_field='width'),
        ),
        migrations.AlterField(
            model_name='newslettertemplate',
            name='scene1_button_label',
            field=models.CharField(default='Learn more', help_text='Label for the button on Scene 1 that leads to Scene 2.', max_length=50),
        ),
    ]
