# Generated by Django 2.1.7 on 2019-03-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20190321_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpletemplate',
            name='button_background_color',
            field=models.CharField(blank=True, help_text='The text color of the button. Valid CSS color.', max_length=20),
        ),
    ]
