# Generated by Django 2.1.7 on 2019-04-01 09:15

from django.db import migrations, models
import snippets.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_simpletemplate_button_background_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(height_field='height', help_text='PNGs only. Note that updating the image will update all snippets using this image.', upload_to=snippets.base.models._generate_filename, width_field='width'),
        ),
    ]
