# Generated by Django 2.1.7 on 2019-04-03 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20190402_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsonsnippet',
            name='client_match_rules',
        ),
        migrations.RemoveField(
            model_name='jsonsnippet',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='jsonsnippet',
            name='locales',
        ),
        migrations.DeleteModel(
            name='JSONSnippet',
        ),
    ]
