# Generated by Django 2.2 on 2019-04-12 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20190403_0630'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleBelowSearchTemplate',
            fields=[
                ('template_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Template')),
                ('text', models.TextField(help_text='Main body text of snippet. HTML subset allowed: i, b, u, strong, em, br')),
                ('block_button_text', models.CharField(default='Remove this', help_text='Tooltip text used for dismiss button.', max_length=50)),
                ('do_not_autoblock', models.BooleanField(blank=True, default=False, help_text='Used to prevent blocking the snippet after the CTA (link or button) has been clicked.')),
                ('icon', models.ForeignKey(help_text='Snippet icon. 192x192px PNG.', on_delete=django.db.models.deletion.PROTECT, related_name='simple_below_search_icons', to='base.Icon')),
            ],
            bases=('base.template',),
        ),
    ]
