# Generated by Django 2.1.7 on 2019-04-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_simplebelowsearchtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='client_option_addon_check_type',
            field=models.CharField(default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_addon_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_bookmarks_count_lower_bound',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_bookmarks_count_upper_bound',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_has_fxaccount',
            field=models.CharField(default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_is_default_browser',
            field=models.CharField(default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_is_developer',
            field=models.CharField(default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_profileage_lower_bound',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_profileage_upper_bound',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_screen_resolutions',
            field=models.CharField(default='0-1024;1024-1920;1920-50000', max_length=150),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_sessionage_lower_bound',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_sessionage_upper_bound',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_version_lower_bound',
            field=models.CharField(default='any', max_length=20),
        ),
        migrations.AddField(
            model_name='snippet',
            name='client_option_version_upper_bound',
            field=models.CharField(default='any', max_length=20),
        ),
    ]
