# Generated by Django 2.1.7 on 2019-04-04 07:48

from django.db import migrations


def migrate_client_options(apps, schema_editor):
    Snippet = apps.get_model('base', 'Snippet')
    attrs = [
        'version_lower_bound',
        'version_upper_bound',
        'has_fxaccount',
        'is_developer',
        'is_default_browser',
        'profileage_lower_bound',
        'profileage_upper_bound',
        'sessionage_lower_bound',
        'sessionage_upper_bound',
        'bookmarks_count_lower_bound',
        'bookmarks_count_upper_bound',
        'addon_check_type',
        'addon_name',
        'screen_resolutions',
    ]

    for snippet in Snippet.objects.all().reverse():
        for attr in attrs:
            setattr(snippet, 'client_option_{}'.format(attr), snippet.client_options.get(attr, ''))
            snippet.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20190404_0806'),
    ]

    operations = [
        migrations.RunPython(migrate_client_options, noop)
    ]
