# Generated by Django 2.1.7 on 2019-04-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20190404_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='filtr_browser_addon',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_country',
            field=models.CharField(blank=True, default='', max_length=1250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_current_search_engine',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_firefox_version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_is_default_browser',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_is_developer',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_previous_session_end',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_profile_age_created',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_total_bookmarks_count',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_updates_autodownload_enabled',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_updates_enabled',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_uses_firefox_sync',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
