# Generated by Django 2.1.7 on 2019-04-04 10:52

from django.db import migrations


def migrate_jexl(apps, schema_editor):
    Target = apps.get_model('base', 'Target')

    attrs = [
        'filtr_is_default_browser',
        'filtr_profile_age_created',
        'filtr_firefox_version',
        'filtr_previous_session_end',
        'filtr_uses_firefox_sync',
        'filtr_country',
        'filtr_is_developer',
        'filtr_updates_enabled',
        'filtr_updates_autodownload_enabled',
        'filtr_current_search_engine',
        'filtr_browser_addon',
        'filtr_total_bookmarks_count',
    ]

    for target in Target.objects.all().reverse():
        for attr in attrs:
            setattr(target, attr, target.jexl.get(attr, ''))
            target.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0086_auto_20190404_1052'),
    ]

    operations = [
        migrations.RunPython(migrate_jexl, noop)
    ]
