# Generated by Django 2.2 on 2019-04-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_auto_20190404_1052'),
    ]

    operations = [
        # Part the Dynamic Column Removal Effort (Issue #940)
    ]
