# Generated by Django 2.2 on 2019-05-09 12:47

import django.core.validators
from django.db import migrations, models
import snippets.base.models
import snippets.base.validators


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20190415_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrsnippet',
            name='weight',
            field=models.IntegerField(choices=[(2, 'Appear 1/50th as often as an average snippet'), (5, 'Appear 1/20th as often as an average snippet'), (10, 'Appear 1/10th as often as an average snippet'), (33, 'Appear 1/3rd as often as an average snippet'), (50, 'Appear half as often as an average snippet'), (66, 'Appear 2/3rds as often as an average snippet'), (100, 'Appear as often as an average snippet'), (150, 'Appear 1.5 times as often as an average snippet'), (200, 'Appear twice as often as an average snippet'), (300, 'Appear three times as often as an average snippet')], default=100, help_text='How often should this snippet be shown to users?'),
        ),
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='donation_form_url',
            field=models.URLField(default='https://donate.mozilla.org/?utm_source=desktop-snippet&utm_medium=snippet', max_length=500, validators=[django.core.validators.URLValidator(schemes=['https'])]),
        ),
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(height_field='height', help_text='PNG only. Note that updating the image will update all snippets using this image.', upload_to=snippets.base.models._generate_filename, validators=[snippets.base.validators.validate_image_format], width_field='width'),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='weight',
            field=models.IntegerField(choices=[(2, 'Appear 1/50th as often as an average snippet'), (5, 'Appear 1/20th as often as an average snippet'), (10, 'Appear 1/10th as often as an average snippet'), (33, 'Appear 1/3rd as often as an average snippet'), (50, 'Appear half as often as an average snippet'), (66, 'Appear 2/3rds as often as an average snippet'), (100, 'Appear as often as an average snippet'), (150, 'Appear 1.5 times as often as an average snippet'), (200, 'Appear twice as often as an average snippet'), (300, 'Appear three times as often as an average snippet')], default=100, help_text='How often should this snippet be shown to users?', verbose_name='Prevalence'),
        ),
    ]
