# Generated by Django 2.2 on 2019-05-09 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0089_auto_20190509_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='filtr_desktop_devices_count',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_mobile_devices_count',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
        migrations.AddField(
            model_name='target',
            name='filtr_total_devices_count',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
