# Generated by Django 2.2.1 on 2019-06-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0090_auto_20190509_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraisingtemplate',
            name='text',
            field=models.TextField(help_text='Main body text of snippet. HTML subset allowed: i, b, u, strong, em, br'),
        ),
    ]
