# Generated by Django 2.2.1 on 2019-06-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20190610_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asrsnippet',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snippets', to='base.Campaign'),
        ),
        migrations.AlterField(
            model_name='asrsnippet',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='snippets', to='base.Category'),
        ),
        migrations.AlterField(
            model_name='asrsnippet',
            name='targets',
            field=models.ManyToManyField(blank=True, default=None, related_name='snippets', to='base.Target'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='slug',
            field=models.SlugField(help_text='Campaign slug. Will be added in the stats ping. Will be used for snippet blocking if set.', max_length=255, unique=True),
        ),
    ]
