# Generated by Django 2.2.1 on 2019-06-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_auto_20190606_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendtodevicetemplate',
            name='locale',
            field=models.CharField(default='EN', help_text='Two to five character string for the locale code. Default "EN".', max_length=10),
        ),
    ]
