# Generated by Django 2.2.2 on 2019-06-27 13:01

import django.core.validators
from django.db import migrations, models
import snippets.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_auto_20190619_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icon',
            name='image',
            field=models.ImageField(height_field='height', help_text='PNG only. A reasonable file size is about 5 KiB. Note that updating the image will update all snippets using this image.', upload_to=snippets.base.models._generate_filename, width_field='width'),
        ),
        migrations.AlterField(
            model_name='locale',
            name='code',
            field=models.CharField(help_text='Comma separated list of locales with or without territory information. E.g `en-us` and `es-mx,es-ar`', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(regex='^,?([A-Za-z-]+,?)+$')]),
        ),
    ]
